language: go
go_import_path: github.com/pvotal-tech/go-uof-sdk
os:
    - linux
    - osx
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -package=./ -service=travis-ci